services:
  redis:
    image: redis:7.4.10
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-change-me-dev-only}"]
    ports:
      - "6379:6379"
    healthcheck: # Make sure redis container ready
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD:-change-me-dev-only} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BROKER_URL=redis://redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-change-me-dev-only}
      - WHISPER_URL=http://whisper-service:3000
      - LLM_MODEL=llama3.2
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
      whisper-service:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads

  celery:
    build: .
    command: python -m celery -A worker.tasks worker --loglevel=info --pool=solo
    environment:
      - BROKER_URL=redis://redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-change-me-dev-only}
      - WHISPER_URL=http://whisper-service:3000
      - OLLAMA_HOST=http://ollama:11434
      - LLM_MODEL=llama3.2
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
      whisper-service:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads

  celery-beat:
    build: .
    command: python -m celery -A worker.tasks beat --loglevel=info
    environment:
      - BROKER_URL=redis://redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-change-me-dev-only}
    depends_on:
      redis:
        condition: service_healthy


  whisper-service:
    build:
      context: .
      dockerfile: Dockerfile.inference
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads


  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes: # storage outside any container
  ollama_data:
  uploads_data: