services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck: # Make sure redis container ready
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0
      - WHISPER_URL=http://whisper-service:3000
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
      whisper-service:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads

  celery:
    build: .
    command: python -m celery -A worker.tasks worker --loglevel=info --pool=solo
    environment:
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0
      - WHISPER_URL=http://whisper-service:3000
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
      whisper-service:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads
        

  whisper-service:
    build:
      context: .
      dockerfile: Dockerfile.inference
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads


  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  flower:
    image: mher/flower
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"

volumes: # storage outside any container
  ollama_data:
  uploads_data: