apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce # In real world need ReadWriteMany for several pods access uploads folder, i.e. maybe use AWS EFS
  resources:
    requests:
      storage: 10Gi