{{- if .Values.redisExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  labels:
    app: redis-exporter
    {{- include "asyncvtp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis-exporter
        image: "{{ .Values.redisExporter.image.repository }}:{{ .Values.redisExporter.image.tag }}"
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: "redis://redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.redis.name }}
              key: {{ .Values.secrets.redis.key }}
        - name: REDIS_EXPORTER_CHECK_KEYS
          value: "celery"
        resources:
          {{- toYaml .Values.redisExporter.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
  labels:
    app: redis-exporter
    {{- include "asyncvtp.labels" . | nindent 4 }}
spec:
  selector:
    app: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
{{- end }}
